In [6]:
import torch
import numpy as np
from torchvision.transforms import ToTensor

In [7]:
t = torch.tensor(np.arange(24).reshape(2,4,3)) #[h,w,c]

In [9]:
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]], dtype=torch.int32)

In [10]:
#[h,w,c] ---> [c,h,w]
# t.view([3,2,2]) #形状[3,2,2] ，但不是[c,h,w]

In [11]:
t.transpose(0,2).transpose(1,2)

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]], dtype=torch.int32)

In [12]:
t.permute(2,0,1)  #[0,1,2] ---> [2,0,1]

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]], dtype=torch.int32)

In [15]:
ToTensor()(t.numpy())

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]], dtype=torch.int32)

In [2]:
from tqdm import tqdm
import time

In [3]:
for i in tqdm(range(100),ascii=True,total=100,desc="自定义的输出为"):
#     print(i)
    time.sleep(0.5)
    pass

自定义的输出为：: 100%|##########################################################################################################################| 100/100 [00:50<00:00,  1.99it/s]


In [14]:
a = t[0,0,:]

In [20]:
b = t[0,1,:]

tensor([3, 4, 2], dtype=torch.int32)

In [22]:
a

tensor([0, 1, 2], dtype=torch.int32)

In [23]:
a.eq(b).float().mean()

tensor(0.3333)