## 张量的创建

In [4]:
import torch
import numpy as np

In [6]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [5]:
torch.tensor(np.arange(15).reshape(3,5))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [7]:
torch.empty([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.ones([3,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## 张量的属性和方法

In [10]:
a = torch.tensor([[[1]]])

In [13]:
a.item()

1

In [15]:
t = a.numpy()

In [17]:
type(t)

numpy.ndarray

In [27]:
a.shape

torch.Size([3, 2, 5])

In [19]:
a.size()

torch.Size([1, 1, 1])

In [20]:
a = torch.tensor(np.arange(30).reshape(3,2,5))

In [21]:
a

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [24]:
a.size(1)

2

In [28]:
a.view([2,3,5])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [29]:
b = torch.tensor(np.arange(15).reshape(3,5))

In [32]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [31]:
b.transpose(0,1)  #直接交换行和列

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]], dtype=torch.int32)

In [34]:
b.view(5,-1) #把b展开之后等分为5分

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [36]:
a  #[3,2,5]

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [35]:
a.transpose(0,1)  #[2,3,5]

tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14],
         [20, 21, 22, 23, 24]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [42]:
b[1,:]

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

In [43]:
b[1]

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

In [44]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [45]:
b[:,1]

tensor([ 1,  6, 11], dtype=torch.int32)

In [46]:
b[:,1] = 100

In [47]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13,  14]], dtype=torch.int32)

In [48]:
b[-1,-1] = 100

In [49]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [50]:
b[-1,-1]

tensor(100, dtype=torch.int32)

In [51]:
c = {100:10,20:10}

In [53]:
c[b.numpy()[-1,-1]]

10

In [54]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [57]:
b.max(dim=-1)[-1]

tensor([1, 1, 4])

In [58]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [63]:
torch.FloatTensor([1,2,3]).dtype

torch.float32

In [72]:
a = torch.tensor([1,2,3])

In [80]:
torch.ones([2,3],dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [81]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [83]:
b.new_ones(size=b.size())

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [85]:
b.zero_()

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [86]:
b

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [88]:
b.add(1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [90]:
b.add_(1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [91]:
b

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

## cuda类型的tensor

In [92]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 

In [93]:
device

device(type='cuda')

In [95]:
a.device

device(type='cpu')

In [99]:
a = a.to(device)

In [100]:
a

tensor([1, 2, 3], device='cuda:0')

In [103]:
a.cpu().device

device(type='cpu')

In [107]:
b = torch.tensor([0,0,0])

In [108]:
b

tensor([0, 0, 0])

In [112]:
a+b.to(device)

tensor([1, 2, 3], device='cuda:0')

In [111]:
a.cpu().numpy()

array([1, 2, 3], dtype=int64)