In [22]:
import torch
import numpy as np

## 进行向前计算

In [5]:
x = torch.ones([2,2],requires_grad=True)

In [6]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
y = x+2

In [8]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [9]:
z = 3*y.pow(2)

In [10]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [11]:
out = z.mean()

In [12]:
out

tensor(27., grad_fn=<MeanBackward1>)

## 进行反向传播

In [13]:
out.backward(retain_graph=True)

In [14]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [19]:
out.backward(retain_graph=True)

In [20]:
x.grad

tensor([[18., 18.],
        [18., 18.]])

## 注意点

In [23]:
t = torch.tensor(np.arange(12).reshape(3,4))

In [24]:
t

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [25]:
t.data

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [28]:
t.data[-1,-1] = 100

In [30]:
t

tensor([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10, 100]], dtype=torch.int32)

In [31]:
out.data

tensor(27.)

In [34]:
out

tensor(27., grad_fn=<MeanBackward1>)

In [35]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [37]:
x.data[-1,-1] = 100

In [39]:
x.numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [49]:
x.data.numpy()

array([[ 1.,  1.],
       [ 1., 10.]], dtype=float32)

In [43]:
x

tensor([[   1.,    1.],
        [   1., 1000.]], requires_grad=True)

In [45]:
a[-1,-1] = 10

In [46]:
a

tensor([[ 1.,  1.],
        [ 1., 10.]])

In [47]:
x

tensor([[ 1.,  1.],
        [ 1., 10.]], requires_grad=True)

# test

In [52]:
a = torch.rand([1])

In [53]:
a

tensor([0.8483])

In [54]:
a.zero_()

tensor([0.])

In [55]:
a

tensor([0.])

In [56]:
w = torch.rand([],requires_grad=True)


In [58]:
print(w.grad)

None
